import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    godotSidebar: [
        {
            type: 'autogenerated',
            dirName: '.',}
    ],
};

export default sidebars;