import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  rovermindSidebar: [{type: 'autogenerated', dirName: '.'}], // [ADICIONADO] sidebar do Curso 3
};

export default sidebars;